export { ProfilePage, initProfilePage } from './profile/ProfilePage';
export { PasswordChange, initPasswordChangePage } from './profile/PasswordChange';
export { AuthorizationPage, initAuthPage } from './authorization';
export { RegistrationPage, initRegistrationPage } from './registration';
export { NotFoundPage, initNotFoundPage, Error500, initErrorPage } from './error';
export { GamePage, initGamePage } from './game';
export { MainPage, initMainPage } from './main';
export { LeaderboardPage, initLeaderBoardPage } from './leaderboard';
export { ForumPage, initForumPage } from './forum';
export { TopicPage, initTopicPage } from './topic';
export { FriendsPageTest, initFriendsPageTest } from './friends';
